name: 📬 Проверка почты

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  check-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Установить зависимости
        run: |
          pip install requests beautifulsoup4

      - name: Запустить скрипт
        env:
          EMAIL: ${{ secrets.EMAIL }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        run: python check_email.py
