name: 📬 Проверка почты каждые 10 минут

on:
  schedule:
    - cron: '*/10 * * * *'   # Каждые 10 минут
  workflow_dispatch:         # Позволяет запустить вручную

jobs:
  check-email:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Получить код
        uses: actions/checkout@v4

      - name: 🐍 Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Установить зависимости (если нужны)
        run: |
          python -m pip install --upgrade pip

      - name: 🏃 Запустить проверку почты
        env:
          EMAIL: ${{ secrets.EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: python check_email.py
